name: Тестирование новеллы на Ren'Py
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Установка Ren'Py
      run: |
        sudo apt-get update
        sudo apt-get install renpy
        
    - name: Клонирование репозитория
      uses: actions/checkout@v2
      
    - name: Запуск тестов
      run: |
        cd 'novel' / 'game' / 'script.rpy'
        
