name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest

  run-core-tests:
    name: Run core tests
    runs-on: ubuntu-latest
